# Generates a C++ source that embeds shared/{data,i18n,art} into the binary (the counterpart of Go's go:embed).
# Usage: cmake -DSHARED_DIR=<repo>/shared -DOUTPUT=<file>.cpp -P embed_shared.cmake
#
# Each file becomes a raw string literal split in chunks: adjacent literals are concatenated by the compiler, and the
# chunks keep every single literal well under the limits some compilers impose.

if(NOT SHARED_DIR OR NOT OUTPUT)
	message(FATAL_ERROR "SHARED_DIR and OUTPUT are required")
endif()

set(chunk_size 4000)
set(delimiter "rpg")

file(GLOB_RECURSE files RELATIVE "${SHARED_DIR}"
	"${SHARED_DIR}/data/*.json" "${SHARED_DIR}/i18n/*.json" "${SHARED_DIR}/art/*.txt")
list(SORT files)

set(body "")
foreach(relative IN LISTS files)
	file(READ "${SHARED_DIR}/${relative}" content)
	# Line endings are normalised so a CRLF checkout embeds exactly the same bytes as an LF one.
	string(REPLACE "\r\n" "\n" content "${content}")
	string(FIND "${content}" ")${delimiter}\"" clash)
	if(NOT clash EQUAL -1)
		message(FATAL_ERROR "${relative} contains the raw string delimiter )${delimiter}\"")
	endif()

	string(LENGTH "${content}" length)
	set(literal "")
	set(offset 0)
	while(offset LESS length)
		string(SUBSTRING "${content}" ${offset} ${chunk_size} chunk)
		# Cut after the last newline so no UTF-8 sequence is split between two literals.
		string(LENGTH "${chunk}" taken)
		math(EXPR remaining "${length} - ${offset}")
		if(taken LESS remaining)
			string(FIND "${chunk}" "\n" last_newline REVERSE)
			if(last_newline GREATER -1)
				math(EXPR taken "${last_newline} + 1")
				string(SUBSTRING "${chunk}" 0 ${taken} chunk)
			endif()
		endif()
		string(APPEND literal "\n\t\t\tR\"${delimiter}(${chunk})${delimiter}\"")
		math(EXPR offset "${offset} + ${taken}")
	endwhile()
	if(literal STREQUAL "")
		set(literal "\"\"")
	endif()
	string(APPEND body "\t\t{\"${relative}\",${literal}},\n")
endforeach()

set(source "// Generated by cmake/embed_shared.cmake from shared/ — do not edit.
#include \"assets/shared_files.hpp\"

namespace rpg::assets {

const SharedFs& embedded_shared() {
	static const SharedFs files{
${body}	};
	return files;
}

} // namespace rpg::assets
")

# Only touch the file when the content changes, so unrelated rebuilds stay incremental.
if(EXISTS "${OUTPUT}")
	file(READ "${OUTPUT}" previous)
	if(previous STREQUAL source)
		return()
	endif()
endif()
file(WRITE "${OUTPUT}" "${source}")
