# Generates a C source that embeds shared/{data,i18n,art} into the binary (the counterpart of Go's go:embed).
# Usage: cmake -DSHARED_DIR=<repo>/shared -DOUTPUT=<file>.c -P embed_shared.cmake
#
# Each file becomes a `static const unsigned char[]` initialised byte by byte. String literals would be shorter, but
# C only guarantees 4095 characters per literal and has no raw strings; byte arrays have neither problem.

if(NOT SHARED_DIR OR NOT OUTPUT)
	message(FATAL_ERROR "SHARED_DIR and OUTPUT are required")
endif()

file(GLOB_RECURSE files RELATIVE "${SHARED_DIR}"
	"${SHARED_DIR}/data/*.json" "${SHARED_DIR}/i18n/*.json" "${SHARED_DIR}/art/*.txt")
list(SORT files)

set(arrays "")
set(table "")
set(index 0)
foreach(relative IN LISTS files)
	file(READ "${SHARED_DIR}/${relative}" hex HEX)
	string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
	# Line endings are normalised so a CRLF checkout embeds exactly the same bytes as an LF one.
	string(REPLACE "0x0d,0x0a," "0x0a," bytes "${bytes}")
	string(REPLACE "0x0a," "0x0a,\n" bytes "${bytes}")
	string(APPEND arrays "static const unsigned char FILE_${index}[] = {\n${bytes}0x00};\n\n")
	string(APPEND table "\t{\"${relative}\", (const char *)FILE_${index}, sizeof(FILE_${index}) - 1},\n")
	math(EXPR index "${index} + 1")
endforeach()

set(source "// Generated by cmake/embed_shared.cmake from shared/ — do not edit.
#include \"assets/shared_files.h\"

#include <string.h>

${arrays}const SharedFile SHARED_FILES[] = {
${table}};

const size_t SHARED_FILE_COUNT = sizeof(SHARED_FILES) / sizeof(SHARED_FILES[0]);

const char *shared_file(const char *path) {
	for (size_t i = 0; i < SHARED_FILE_COUNT; i++) {
		if (strcmp(SHARED_FILES[i].path, path) == 0) {
			return SHARED_FILES[i].content;
		}
	}
	return NULL;
}
")

# Only touch the file when the content changes, so unrelated rebuilds stay incremental.
if(EXISTS "${OUTPUT}")
	file(READ "${OUTPUT}" previous)
	if(previous STREQUAL source)
		return()
	endif()
endif()
file(WRITE "${OUTPUT}" "${source}")
